[feeds.verge]
url = "https://www.theverge.com"
url_rss = "https://www.theverge.com/rss/index.xml"
source = "Website"
clean_title = true
summarise_content = true

[feeds.veritasium]
source = "Youtube"
clean_title = true
summarise_content = true
