use crate::shared::Category;

pub const fn labels(category: Category) -> &'static [&'static str] {
    match category {
        // Corporate finance, stock markets, and macroeconomics
        Category::Business => &[
            "Business, finance, markets, corporate earnings, company strategy, revenues, profits, and share trading.",
            "Mergers, acquisitions, takeovers, IPOs, restructurings, layoffs, and other major company moves.",
            "Macroeconomics, inflation, interest rates, GDP, recession risks, central banks, and fiscal policy.",
            "Startups, venture capital, private equity, market valuation, and funding rounds.",
            "Jobs, hiring, redundancies, retail conditions, wage pressure, and corporate guidance.",
            "Cryptocurrency, blockchain, digital assets, stablecoins, exchanges, and fintech speculation.",
            "Banking, lenders, insolvency, liquidity pressure, debt, and financial stability.",
            "Supply chains, manufacturing, trade flows, tariffs, exports, and global commerce.",
            "A stock market listing, share sale, or flotation for a company or platform.",
            "Corporate tax, operating costs, employment costs, or a company’s contribution to the economy.",
            "Student careers, apprenticeships, placement schemes, graduate jobs, and employability.",
            "Saving, pensions, household money habits, or financial literacy framed as economic policy.",
        ],
        // Government, parliament, elections, political parties, and military/defence affairs
        Category::Politics => &[
            "Government, parliament, legislation, ministries, public policy, and state decision-making.",
            "Elections, campaigns, polling, manifestos, by-elections, and party competition.",
            "Defence, military affairs, security policy, NATO, troop movements, and armed conflict.",
            "Foreign policy, diplomacy, state visits, sanctions, treaties, and international institutions.",
            "Domestic political figures, leadership contests, cabinet politics, and national political commentary.",
            "Public opinion polls, voting intention, and survey-based political analysis.",
            "Local election results, seat gains and losses, and council or regional politics.",
            "Political controversy, accountability, backlash, apologies, and disputes over conduct.",
            "Wartime escalation, strikes across borders, and major casualty reports.",
            "Congress, Senate, White House, legislatures, and partisan lawmaking in major democracies.",
            "Sanctions, trade restrictions, expulsions, and UN or multilateral resolutions.",
            "Protests, strikes, unions, civil unrest, demonstrations, and collective action.",
            "Migration policy, asylum, border control, deportation, and refugee politics.",
            "Regulation of online platforms, children’s safety online, or social media policy.",
            "A routine polling update, party snapshot, leadership challenge, or candidate list.",
            "Education policy, public regulation, or national public service decisions.",
            "A headline centered on criticism of a prime minister, governing party, opposition leader, or major political plan.",
        ],
        // Courts, crime, police investigations, and criminal justice
        Category::Law => &[
            "Courts, trials, verdicts, judges, juries, lawyers, prosecution, and criminal justice outcomes.",
            "Police investigations, arrests, raids, forensics, and law enforcement probes.",
            "Violent crime, murder, assault, theft, robbery, fraud, embezzlement, and misconduct.",
            "Civil litigation, injunctions, tribunals, appeals, regulatory bans, and lawsuits.",
            "Sentencing, prison terms, and punishments after a criminal case.",
            "Extradition, supreme court rulings, judicial review, constitutional law, and appeals.",
            "Cybercrime, ransomware, money laundering, cartel activity, and financial fraud.",
            "Fatal incidents, shootings, drownings, suspicious deaths, and police inquests.",
            "Rape, child abuse, domestic abuse, safeguarding failures, and other serious abuse cases.",
            "A local emergency involving a fatal fall, stabbing, fire, explosion, missing person, or body recovered from water.",
            "Leaked exams, unlawful conduct, regulatory breaches, or evidence brought before a court.",
            "Consumer rights rulings, criminal prosecutions, or arrests after a serious offence.",
            "Professional misconduct, abuse of trust, or unsafe prescribing by a clinician or official.",
            "Major fires, industrial explosions, or suspected attacks involving emergency services.",
            "Fatal industrial accidents, workplace blasts, or large-scale disaster responses.",
            "A fatal accident or suspicious death investigated after a body is recovered.",
            "Regulatory enforcement against gambling ads, unsafe conduct, or banned commercial activity.",
        ],
        // Clinical medicine and personal health — NHS, diagnosis, treatment, fitness, diet
        Category::Health => &[
            "Clinical medicine, hospitals, surgeries, emergency care, and healthcare systems.",
            "Diagnoses, treatments, chronic disease, prescriptions, pharmaceuticals, and symptoms.",
            "Public health, outbreaks, vaccination, infection control, and epidemiology.",
            "Fitness, nutrition, exercise, diet, mental health, and general wellbeing.",
            "Health risks, addiction, doctor advice, and warnings about harmful behaviour or products.",
            "Brain health, dementia, mental illness, depression, and psychiatry.",
            "Drug trials, medical research, approvals, and pharmaceutical development.",
            "Longevity, biohacking, supplements, metabolic health, diabetes, and weight-loss drugs.",
        ],
        // Entertainment, film, TV, music, celebrities, streaming, and media
        Category::Culture => &[
            "Entertainment news, streaming shows, TV series, trailers, releases, and broadcasters.",
            "Celebrities, actors, musicians, influencers, and wider showbusiness coverage.",
            "Music, concerts, festivals, albums, awards, and live performance coverage.",
            "Arts, theatre, literature, museums, cultural criticism, and reviews.",
            "TV personalities, presenters, reality shows, and broadcasting careers.",
            "Streaming platforms, box office, franchises, and audience viewing habits.",
            "YouTube, TikTok, podcasts, memes, and internet culture.",
            "A story about a band, concert, live performance, album, or touring artist.",
            "A story about a musician, obituary, synthesizer, or music instrument.",
            "Entertainment merchandise, tie-ins, collectibles, puppets, or franchise products.",
        ],
        // Domestic life, cooking, home, fashion, consumer tips, and personal finance
        Category::Lifestyle => &[
            "Home, cooking, recipes, baking, meal prep, and kitchen advice.",
            "Interior design, cleaning, gardening, household management, and property upkeep.",
            "Personal finance, mortgages, rent, bills, savings, pensions, and budgeting.",
            "Fashion, skincare, dating, parenting, travel, and everyday lifestyle advice.",
            "Shopping deals, seasonal sales, discounts, and consumer bargains.",
            "Workplace culture, office life, team-building, and career advice.",
            "Local events, farm shops, community attractions, and rural leisure.",
            "Property, home buying, rentals, hosting, and hotel reviews.",
            "Luxury goods, streetwear, cosmetics, beauty products, and fashion weeks.",
            "Household utilities, energy bills, and cost-of-living advice.",
        ],
        // Cars, transport infrastructure, aviation, and commuting
        Category::Transport => &[
            "Cars, electric vehicles, roads, motorways, and automotive engineering.",
            "Aviation, airlines, airports, flights, and airspace management.",
            "Rail, metro systems, public transit, commuting, and freight shipping.",
            "Ports, container shipping, logistics networks, and delivery distribution.",
            "Self-driving vehicles, drones, micro-mobility, and experimental transport tech.",
            "A road closure, vehicle fire, service upgrade, airline change, or transport disruption.",
        ],
        // Wildlife, ecology, the natural world, and climate — animals, plants, weather, conservation
        Category::Nature => &[
            "Wildlife, ecosystems, biodiversity, endangered species, and conservation.",
            "Climate change, warming, emissions, floods, droughts, and extreme weather.",
            "Environmental science, forestry, ecology, and marine biology.",
            "Weather forecasts, temperature records, heatwaves, rain, and climate conditions.",
            "Heat, cooling, adaptation, and environmental impacts on homes or cities.",
            "Pollution, wastewater, sewage, rivers, and habitat damage.",
            "Renewable energy, recycling, solar, wind, and green infrastructure.",
            "Earthquakes, volcanoes, seismic activity, tsunamis, and geology.",
            "Rainforest restoration, woodland expansion, and rewilding.",
            "A weather story about extremes, records, flooding, or heatwaves.",
        ],
        // Consumer electronics and hardware — phones, laptops, TVs, headphones, wearables
        Category::Technology => &[
            "Consumer electronics, smartphones, laptops, and gadget specifications.",
            "Computer hardware, chips, GPUs, storage, and displays.",
            "Smart home devices, wearables, speakers, and wireless accessories.",
            "TVs, screens, audio equipment, and display technology.",
            "Semiconductors, chipmaking, hardware architecture, and fabs.",
            "VR, AR, smart glasses, and spatial computing hardware.",
            "Fitness trackers, smartwatches, sleep rings, action cameras, and wearables.",
            "A physical tech product such as a camera accessory, laptop add-on, or music gear.",
        ],
        // Software development, coding, and cybersecurity
        Category::Software => &[
            "Software development, coding, programming languages, and application design.",
            "Cybersecurity, hacking, malware, ransomware, exploits, and vulnerabilities.",
            "DevOps, databases, open source, APIs, cloud services, and infrastructure.",
            "Privacy, VPNs, data protection, surveillance, and online security.",
            "Operating systems, Linux, and software licensing or regulation.",
            "Cloud platforms, containers, Kubernetes, and microservices.",
            "Git, GitHub, CI/CD, deployment pipelines, and technical documentation.",
            "Digital identity platforms, online services, and critical digital infrastructure.",
            "Metadata collection, encryption access, VPN products, or data retention law.",
            "Desktop apps, extensions, utilities, and developer tools.",
        ],
        // Artificial intelligence, machine learning, and AI assistants
        Category::AI => &[
            "Artificial intelligence, machine learning, language models, and neural networks.",
            "Generative AI tools, chatbots, prompt design, and image generation.",
            "AI safety, model training, agents, and model evaluation.",
            "AI-powered software features and assistants.",
            "OpenAI, Anthropic, DeepMind, model architectures, fine-tuning, and training data.",
            "Computer vision, natural language processing, reinforcement learning, and benchmarks.",
            "A language model release, benchmark result, pricing update, or open-weights announcement.",
        ],
        // Scientific research, astronomy, biology, and academic discovery
        Category::Science => &[
            "Scientific research, laboratory experiments, discoveries, hypotheses, and journals.",
            "Space exploration, astronomy, telescopes, rockets, satellites, and planets.",
            "Physics, chemistry, biology, genetics, and molecular research.",
            "Archaeology, historical research, and ancient remains.",
            "Gene editing, DNA sequencing, and evolutionary biology.",
            "Particle physics, dark matter, black holes, and astrophysics.",
            "Spaceflight research, astronauts, Moon missions, and equipment for use in space.",
        ],
        // Physical competitive sports and athletic leagues
        Category::Sports => &[
            "Football, leagues, fixtures, tournaments, goals, and team lineups.",
            "Cricket, tennis, rugby, golf, and other competitive sports.",
            "Sports commentary, team selection, transfers, squads, and season reviews.",
            "Olympics, marathons, motorsport, and podium finishes.",
            "Race standings, results, and other sporting events.",
            "Basketball, American football, baseball, and athlete contracts.",
            "MMA, boxing, title fights, and doping cases.",
            "Motor racing, Formula One, TT events, riders, circuits, and race results.",
            "Tennis tournaments, draws, players, and sporting performance.",
        ],
        // Video games, gaming culture, esports, and game releases
        Category::Gaming => &[
            "Video games, releases, gameplay, console hardware, and esports.",
            "Gaming culture, streaming, multiplayer, and indie studios.",
            "PlayStation, Xbox, Nintendo, PC gaming, handhelds, and emulators.",
            "MMORPGs, shooters, speedrunning, mods, and gaming communities.",
        ],
    }
}
