pub fn labels(importance: &str) -> &'static [&'static str] {
    match importance {
        "important" => &[
            "Macroeconomic state directives and fiscal legislation: statutory national economic systems, country-wide housing financial initiatives, state-backed financial subsidy programs, national first-buyer loan schemes, binding multi-million regulatory price caps, mandatory utility adjustments, household energy price cap increases, major global trade realignments.",
            "Sovereign political governance and legislative changes: constitutional law amendments, state executive appointments, parliamentary legislation updates, national civil service systemic re-organizations, public ownership polling, nationalisation of essential utilities.",
            "Geopolitical intelligence strategy and transnational defense: high-level intelligence agency directives, sovereign state security alerts, cross-border defense alliances, national democratic protection strategies, macro-threat assessments.",
            "Widespread societal transformations and demographics: country-wide census shifts, generational birth rate fluctuations, macro demographic fertility trends, broad public safety crises, extensive public welfare vulnerabilities.",
            "Generational scientific and technical achievements: foundational technological breakthroughs, global quantum computing research access, international scientific collaboration programs, paradigm-shifting medical discoveries.",
            "Severe national emergencies and massive infrastructure disasters: mass-fatality structural tragedies, lethal school disasters, school fires, student deaths, casualty counts, search-and-rescue operations, lethal multi-casualty disasters, critical cross-border energy infrastructure updates, country-wide environmental litigation prosecutions.",
            "Macro ecological preservation: extensive statutory conservation efforts, sweeping river system safety mandates, high-level wildlife protections, widespread protected species persecution, national wildlife crime evidence.",
            "Major institutional education and research access: university-wide undergraduate employment guarantees, large academic placement programmes, broad student career infrastructure, national research teams using advanced quantum hardware.",
            "Household affordability and utility pressure: cost-of-living pressure, household energy price rises, bill shock, regulated price cap increases, domestic affordability crisis, fuel bills, heating bills, consumer price pressure.",
        ],
        "unimportant" => &[
            "Routine consumer lifestyle and retail commerce: personal shopping guides, household appliance discounts, commercial furniture promotions, general electronics product updates, consumer car rumors, localized retail shopping events, personal culinary trends, backyard grilling guides, tomato gardening tips, mattress sale recommendations, shoe discount roundups, gaming discounts, tablet price drops, television sale lists, smart ring rumors, sale pages, bargain roundups, discount guides, retail promotions, streaming guides.",
            "Niche technical walkthroughs, internal software configurations, and low-level programming code adjustments: localized digital setups, code compiler optimizations, compiler internals, register allocator details, interference graphs, linear scan, method inlining, JIT internals, personal development workspace tools, isolated runtime programming tutorials, software documentation extracts, prompt optimization strategies, prompt tricks, productivity hacks, multitasking tips, individual computer networking advice, wireless router signal fixes, camera app feature releases.",
            "Localized community incidents and municipal occurrences: regional neighborhood disputes, local council administrative arguments, municipal park code updates, regional leisure destination news.",
            "Individual personal health updates: single-person medical diagnoses, isolated clinical treatments, personal health recovery profiles, individual advisory group nominations, astronaut biographies, crew member profiles, human-interest science profiles.",
            "Minor pop-culture entertainment and streaming media: commercial television broadcast schedules, streaming media series reviews, free online video viewing options, celebrity pop-culture reporting, entertainment watch guides, drama streaming availability.",
            "Localized sports friction and field altercations: competitive athletic handshake arguments, grand slam referee disputes, single-match scoreboards, regional tournament formatting.",
            "Isolated local criminal incidents and singular offences: localized felony arrests, single-incident park accidents, localized beach law enforcement interventions, municipal anti-social behavior warnings.",
            "Minor regional conservation activities and local park upkeep: regional public access maintenance, localized volunteer community cleanups, municipal landmark preservation efforts, minor regional wildlife tracking, localized pollution surveying, chalk landmark restoration, beach litter complaints.",
            "Tactical combat updates, defense site liabilities, and local border actions: field military maneuvers, specific local evacuation bulletins, localized territorial artillery strikes, active tactical field deployments, regional corporate environmental liability cases.",
        ],
        _ => &[],
    }
}
