pub fn labels(importance: &str) -> &'static [&'static str] {
    match importance {
        "important" => &[
            "education programme, university careers, student skills, employment experience.",
            "electric vehicle, car launch, manufacturer strategy, vehicle electrification.",
            "habitat protection, public access, wildlife land, conservation purchase.",
            "security warning, hostile state, infrastructure threat, democracy threat, intelligence chief.",
            "school fire, students killed, casualties, blaze, search-and-rescue, public emergency.",
            "energy bills, price cap, households pay more, national prices, cost of living.",
            "temperature records, climate change, extreme heat, climate extremes, major weather impact.",
            "Government, policy, and public institutions with broad consequence: national decisions, legislation, court rulings, regulation, election outcomes, rights, public services, public funds, housing support, first-time buyers, interest-free loans, education access, university-wide work placements, healthcare, schools, civil service capacity, public sector staffing, and infrastructure affecting communities.",
            "Large-scale risk, security, and emergency harm: war, terrorism, epidemics, disasters, mass casualties, national security warnings, hostile state activity, democracy threats, infrastructure attacks, public emergencies, deadly school fires, multiple casualties, student deaths, search-and-rescue operations, safeguarding failures, serious offences against young people, and police investigations.",
            "First-time buyers, housing fund, interest-free loans, public funds, government support, affordability, home ownership, and national housing policy.",
            "Civic support and national leadership stories: public housing funds, government-backed loans, first homes schemes, national political figures, presidential debates, heads of state, intelligence chiefs, hostile state warnings, and public decisions affecting many citizens.",
            "Deadly emergencies and major public safety events: school blazes, multiple students killed, mass casualty incidents, search-and-rescue operations, large fires, and safeguarding cases requiring police action.",
            "Systemic accountability and institutional failure: criminal trials, convictions, inquiries, corruption, major lawsuits, corporate liability, government legal action, institutional failure, NHS trust failures, patient safety failures, rights violations, systemic injustice, and official investigations with public consequences.",
            "Economic, environmental, medical, scientific, or industry impact beyond one consumer item: national prices, tax changes, interest rates, job losses, household bills, energy price caps, inflation, cost of living, climate extremes, temperature records, ecosystem damage, serious health risks, treatment breakthroughs, major discoveries, energy transition, vehicle electrification, manufacturer strategy, and sector-wide technology adoption.",
        ],
        "unimportant" => &[
            "local land purchase, council project, local public access.",
            "free online watch, streaming guide, television season, entertainment preview.",
            "home garden advice, planting guide, growing tips.",
            "router tip, Wi-Fi fix, aluminum foil, household tech trick.",
            "astronaut profile, crew announcement, routine space profile.",
            "ChatGPT prompt tip, productivity hack, personal workflow advice.",
            "dog attack, local death, individual incident, local tragedy, sentencing, jail warning.",
            "smart ring, wearable rumour, battery life concern, product teaser, minor gadget update.",
            "compiler internals, register allocator, developer blog, Emacs, niche software article.",
            "sports row, handshake dispute, heated exchange, match controversy, tournament chatter.",
            "mattress sale, shopping deal, product discount, consumer recommendation, limited-time bargain.",
            "Routine consumer and shopping content: sales, deals, discounts, coupons, product roundups, shopping recommendations, mattress sales, clothing, shoes, appliances, wearables, phones, accessories, reviews, comparisons, teasers, minor updates, gadget specifications, product concerns, battery concerns, consumer technology refreshes, setup guides, home networking tips, device workarounds, and household tech fixes.",
            "Entertainment, games, sports, and lifestyle service journalism: streaming guides, series previews, watch-online articles, film rankings, celebrity chatter, pop culture, game reviews, PS5 games on sale, console bargains, promotional discounts, cooking, cleaning, gardening, decorating, exercise tips, beauty, fashion, dating, holiday advice, home comfort, routine sports coverage, match previews, normal results, player comments, sports rows, handshake disputes, and tournament chatter.",
            "Small local incidents or narrow human-interest stories with limited wider consequence: local deaths, bodies recovered from water, flowers laid, local tragedies, dog attacks, inquests, animal stories, beach wash-ups, discarded catch, minor public safety updates, local emergency reports, routine crew announcements, astronaut biographies, scientist profiles, and institutional profile pieces.",
            "Niche professional, political, and productivity updates: software tutorials, developer blog posts, Emacs articles, register allocator notes, compiler internals, AI prompt tips, workflow tricks, multitasking advice, model price comparisons, AI benchmark scores, opinion polls, candidate lists, speech reactions, party speculation, day-to-day debate, and company marketing.",
            "Routine local legal or consumer disputes: local dog attack sentencing, individual lawsuits, corporate claims about contamination, local police arrests, isolated beach incidents, routine court follow-up, and cases with limited national policy impact.",
            "Low-stakes technology and promotion: smart ring rumours, battery-life worries, router tricks, aluminum foil Wi-Fi tips, app launches, developer internals, games discounts, sale promotions, gadget deals, and personal productivity hacks.",
            "Entertainment guide, free streaming, watch online, television season, crime thriller series, mattress discount, product deal, limited-time sale, and shopping recommendation.",
            "Local tragedy, individual fatal dog attack, flowers laid, body recovered, beach wash-up, discarded catch, local arrests, and routine police report.",
        ],
        _ => &[],
    }
}
