pub const fn labels(positive: bool) -> &'static [&'static str] {
    if positive {
        &[
            "Macroeconomic state directives and fiscal legislation: statutory national economic systems, country-wide housing financial initiatives, state-backed financial subsidy programs, national first-buyer loan schemes, binding multi-million regulatory price caps, mandatory utility adjustments, household energy price cap increases, major global trade realignments.",
            "National public policy and security significance: devolved government financial schemes, household loan programmes, sovereign infrastructure threats, intelligence chief warnings, major wartime hospital casualties, large-scale conservation crime, protected species persecution.",
            "Sovereign political governance and legislative changes: constitutional law amendments, state executive appointments, parliamentary legislation updates, national civil service systemic re-organizations, public ownership polling, nationalisation of essential utilities.",
            "Geopolitical intelligence strategy and transnational defense: high-level intelligence agency directives, sovereign state security alerts, cross-border defense alliances, national democratic protection strategies, macro-threat assessments.",
            "War, climate, and systemic hazard crises: active war casualties, hospital strike deaths, at least five children killed, multiple child casualties, targeted commanders, urban hospital casualties, active combat-zone hospital attacks, major defense intelligence warnings, national infrastructure targeting, democracy subversion, record-breaking temperature extremes, continental heat domes, protected reserve flood failures, critical habitat destruction, war-ending diplomatic refusal.",
            "Widespread societal transformations and demographics: country-wide census shifts, generational birth rate fluctuations, macro demographic fertility trends, broad public safety crises, extensive public welfare vulnerabilities.",
            "Generational scientific and technical achievements: foundational technological breakthroughs, global quantum computing research access, international scientific collaboration programs, paradigm-shifting medical discoveries.",
            "Severe national emergencies and massive infrastructure disasters: mass-fatality structural tragedies, lethal school disasters, school fires, student deaths, casualty counts, search-and-rescue operations, lethal multi-casualty disasters, active war casualties, critical cross-border energy infrastructure updates, country-wide environmental litigation prosecutions.",
            "Macro ecological preservation: extensive statutory conservation efforts, sweeping river system safety mandates, high-level wildlife protections, widespread protected species persecution, national wildlife crime evidence.",
            "Major institutional education and research access: university-wide undergraduate employment guarantees, large academic placement programmes, broad student career infrastructure, national research teams using advanced quantum hardware.",
            "Household affordability and utility pressure: cost-of-living pressure, household energy price rises, bill shock, regulated price cap increases, domestic affordability crisis, fuel bills, heating bills, consumer price pressure.",
            "School disasters and fatal emergency response: school fires, school blazes, student fatalities, casualty counts, search-and-rescue operations, mass-casualty fire scenes, child safety emergencies, urgent evacuation response.",
        ]
    } else {
        &[
            "Routine consumer lifestyle and retail commerce: personal shopping guides, household appliance discounts, commercial furniture promotions, general electronics product updates, consumer car rumors, localized retail shopping events, personal culinary trends, backyard grilling guides, tomato gardening tips, mattress sale recommendations, shoe discount roundups, sneaker sale roundups, gaming discounts, tablet price drops, television sale lists, smart ring rumors, wearable rumors, sale pages, bargain roundups, discount guides, retail promotions, streaming guides.",
            "Niche technical walkthroughs, internal software configurations, and low-level programming code adjustments: localized digital setups, code compiler optimizations, compiler internals, register allocator details, interference graphs, linear scan, method inlining, JIT internals, personal development workspace tools, isolated runtime programming tutorials, software documentation extracts, prompt optimization strategies, prompt tricks, productivity hacks, multitasking tips, individual computer networking advice, wireless router signal fixes, camera app feature releases.",
            "Localized community incidents and municipal occurrences: regional neighborhood disputes, local council administrative arguments, municipal park code updates, isolated local tragedies, single-person accidents, individual body recovery, local memorial flowers, individual animal attack fatalities, dog attack incidents, local fatal dog attacks, beach litter complaints, regional leisure destination news.",
            "Individual personal health updates: single-person medical diagnoses, isolated clinical treatments, personal health recovery profiles, individual advisory group nominations, astronaut biographies, crew member profiles, human-interest science profiles.",
            "Minor pop-culture entertainment and streaming media: commercial television broadcast schedules, streaming media series reviews, free online video viewing options, celebrity pop-culture reporting, entertainment watch guides, drama streaming availability.",
            "Localized sports friction and field altercations: competitive athletic handshake arguments, grand slam referee disputes, single-match scoreboards, regional tournament formatting.",
            "Sports media access instructions: match streaming guides, free player access, subscription sports viewing, broadcast access explainers, fixture viewing instructions, live match access pages, free sports stream instructions.",
            "Isolated local criminal incidents and singular offences: localized felony arrests, single-incident park accidents, localized beach law enforcement interventions, municipal anti-social behavior warnings.",
            "Minor regional conservation activities and local park upkeep: regional public access maintenance, localized volunteer community cleanups, municipal landmark preservation efforts, minor regional wildlife tracking, localized pollution surveying, chalk landmark restoration, beach litter complaints.",
            "Tactical combat updates, defense site liabilities, and local border actions: field military maneuvers, specific local evacuation bulletins, localized territorial artillery strikes, active tactical field deployments, regional corporate environmental liability cases.",
            "Routine consumer promotions, deal pages, and media access: last-chance sales, price-drop listicles, discount roundups, seasonal bargain guides, retail promotion articles, promotional sale pages, mattress deal articles, wearable speculation, watch guides, streaming access guides, weekend binge lists, streaming watchlists, where to watch, watch online, stream free, stream free guides, episode access guides, season availability, broadcast timing, smart ring speculation, tablet rumors, TV discount stories, footwear sale posts, sneaker deal posts, appliance offer pages, product launch chatter, retail launch previews, tournament tie-in sales, kickoff promotions, world cup sale pages, free player access guides.",
            "Routine industry events and social posts: conference announcements, panel invitations, lightning talk schedules, benchmark meetups, event reminders, leaderboard promotional posts, company community updates, in-person discussion invitations, technical meetup announcements.",
            "Consumer gadget rumors and product teaser coverage: smart ring speculation, wearable gadget rumors, tablet rumors, TV discount stories, footwear sale posts, mattress deal articles, appliance offer pages, product launch chatter, retail launch previews.",
            "Entertainment watch pages and streaming instructions: where to watch, watch online, stream free, episode access guides, season availability, broadcast timing, weekend binge lists, watchlist additions, movie marathon suggestions, crime-thriller series viewing tips, drama streaming availability.",
            "Backyard cooking and hobby guides: backyard grilling guides, grilling accessories, home cooking tips, tomato gardening tips, practical hobby advice, seasonal lifestyle tutorials.",
            "Low-level engineering notes and everyday tech troubleshooting: compiler internals, register allocators, JIT implementation details, method inlining, interference graphs, linear scan, router fixes, Wi-Fi dead zone tips, prompt tricks, productivity hacks, chat prompts, multitasking hacks, prioritization tricks, workflow shortcuts, time-management tips, routine organization advice, personal prompt advice.",
        ]
    }
}
