use crate::shared::Region;

pub const fn labels(region: Region) -> &'static [&'static str] {
    match region {
        Region::Global => &[
            "An international story involving several countries or a global institution.",
            "A story with no specified geographic location or regional focus.",
            "A consumer technology or entertainment story released for a global audience.",
            "A worldwide business, science, or internet story with global relevance.",
            "A location-free product review, shopping guide, streaming recommendation, gadget release, or software article.",
            "A global technology, artificial intelligence, gaming, music, or online security product announcement.",
            "A software engineering essay, developer tool discussion, AI benchmark post, or app feature with no stated place.",
        ],
        Region::UnitedKingdom => &[
            "A national story about Britain or the United Kingdom as a whole.",
            "A UK government story involving Westminster, Downing Street, or Parliament.",
            "A story about British public opinion, the UK economy, or a UK-wide institution.",
            "A policy or event affecting people across the nations of the United Kingdom.",
            "A British national story involving Ofgem, Ofcom, GCHQ, the English Channel, UK railways, or UK-wide social media rules.",
            "A UK election poll, Westminster voting intention, Labour, Reform UK, or national party policy story.",
            "A UK story about migrants crossing the English Channel, national child online-safety proposals, or UK government action.",
        ],
        Region::England => &[
            "A story about England or the English national government and public services.",
            "A local story in London, Manchester, Birmingham, Liverpool, or another English city.",
            "A story about an English county, council, school, court, river, or community.",
            "A story about elections, policing, weather, or infrastructure specifically in England.",
            "A local English story in Hackney, Sheffield, Sunderland, Norwich, Lancaster, Fordingbridge, Golders Green, or the River Wandle.",
            "A story about Makerfield, Wigan, Herefordshire, Dorset, Worcestershire, Kew Gardens, or an English council by-election.",
            "An English story involving Sheffield, Manchester, Sunderland, Newcastle, north-east England NHS services, or the River Wandle.",
        ],
        Region::Scotland => &[
            "A national story about Scotland or the Scottish public.",
            "A political story involving Holyrood or the Scottish Government.",
            "A local story in Edinburgh, Glasgow, Aberdeen, Dundee, or the Highlands.",
            "A Scottish story about courts, councils, nature, business, or public services.",
            "A Scottish story involving the SNP, Holyrood, Arbroath, Aberdeen, Peebles, or the A9 near Dunkeld.",
        ],
        Region::Wales => &[
            "A national story about Wales or the Welsh public.",
            "A political story involving the Senedd or Welsh Government.",
            "A local story in Cardiff, Swansea, Newport, Wrexham, or a Welsh community.",
            "A Welsh story about policing, weather, transport, education, or public services.",
            "A Welsh story involving Swansea, Fairwood, Cardiff, the Senedd, Eryri, Snowdonia, or a Welsh health board.",
            "A council by-election or local political story in Fairwood, Swansea is located in Wales.",
        ],
        Region::Ireland => &[
            "A story located anywhere on the island of Ireland, including Northern Ireland or the Republic of Ireland.",
            "A Northern Ireland story involving Belfast, Derry, Ulster, Stormont, the DUP, or Northern Irish public services.",
            "A national story about the Republic of Ireland or the Irish public.",
            "A government story involving Dublin, the Dail, or the Taoiseach.",
            "A local story in Dublin, Cork, Galway, Limerick, or another Irish place.",
            "An Irish story about business, courts, health, culture, or public services.",
        ],
        Region::UnitedStates => &[
            "A national story about the United States or the American public.",
            "A US government story involving Washington, Congress, the White House, or federal agencies.",
            "A local story in an American state or city such as California, Texas, or New York.",
            "A US story about business, courts, transport, schools, or public policy.",
            "An American story involving Texas elections, a US Senate primary, Washington state, Longview, an NFL player, or an American school district.",
            "A US company or federal story involving NASA, American Airlines, Charter Communications, Meta, or SpaceX.",
            "A fatal incident, explosion, court case, or public event in Longview, Washington or another named US city.",
        ],
        Region::Canada => &[
            "A national story about Canada or the Canadian public.",
            "A Canadian government story involving Ottawa or Parliament.",
            "A local story in Ontario, Quebec, Alberta, British Columbia, Toronto, or Montreal.",
            "A Canadian story about business, courts, climate, health, or public services.",
            "A Canadian federal policy story involving a Canadian bill, privacy, security, Ottawa, or Canadian legislation.",
        ],
        Region::NorthAmerica => &[
            "A North American story affecting both the United States and Canada.",
            "A continental trade or transport story spanning North American borders.",
            "A regional climate or energy story across North America.",
            "A story explicitly about North American markets, sport, or industry.",
        ],
        Region::LatinAmerica => &[
            "A regional story about Latin America, Central America, South America, or the Caribbean.",
            "A national story about Brazil, Argentina, Chile, Colombia, Peru, or Venezuela.",
            "A story about Mexico, Cuba, Haiti, or another Caribbean or Central American country.",
            "A Latin American story about elections, economy, security, climate, or culture.",
        ],
        Region::WesternEurope => &[
            "A Western European or European Union story involving Brussels or EU institutions.",
            "A national story about France, Germany, Spain, Italy, or Portugal.",
            "A story about the Netherlands, Belgium, Austria, Switzerland, or Nordic Europe.",
            "A western European story about policy, economy, security, climate, or culture.",
            "A story located in Spain, Italy, France, Leipzig, Germany, or continental western Europe.",
            "A Spanish regulatory ban, an Italian court ruling, a sporting incident in Leipzig, or extreme weather in western Europe.",
        ],
        Region::EasternEurope => &[
            "An eastern European story involving Ukraine, Kyiv, Russia, or Moscow.",
            "A national story about Poland, Romania, Hungary, Czechia, or Slovakia.",
            "A story involving Moldova, Belarus, the Baltics, or the Balkans.",
            "An eastern European story about war, security, politics, economy, or society.",
        ],
        Region::MiddleEastNorthAfrica => &[
            "A Middle Eastern story involving Israel, Palestine, Iran, Iraq, Syria, or Lebanon.",
            "A Gulf story involving Saudi Arabia, the United Arab Emirates, Qatar, or Yemen.",
            "A North African story involving Egypt, Morocco, Algeria, Tunisia, or Libya.",
            "A MENA story about conflict, diplomacy, energy, society, business, or culture.",
            "A story about Gaza City, Hamas, Hezbollah, Lebanon, Israel, Morocco, or conflict in the Middle East.",
            "A sports event or national story explicitly involving Morocco is located in North Africa.",
        ],
        Region::SubSaharanAfrica => &[
            "A sub-Saharan African story involving Nigeria, Ghana, Senegal, or west Africa.",
            "An east African story involving Kenya, Ethiopia, Uganda, Tanzania, or Rwanda.",
            "A southern or central African story involving South Africa, Zimbabwe, or Congo.",
            "An African story south of the Sahara about politics, health, business, climate, or society.",
        ],
        Region::SouthAsia => &[
            "A South Asian story involving India, New Delhi, Mumbai, or Indian institutions.",
            "A story involving Pakistan, Bangladesh, Sri Lanka, Nepal, Bhutan, or the Maldives.",
            "A regional story about South Asian politics, economy, security, climate, or society.",
            "A story located in Afghanistan, Kashmir, Punjab, or elsewhere in the South Asian region.",
        ],
        Region::EastAsia => &[
            "An East Asian story involving China, Beijing, Shanghai, or Hong Kong.",
            "A Japanese story involving Tokyo or Japanese public institutions and companies.",
            "A Korean story involving South Korea, North Korea, Seoul, or Pyongyang.",
            "A regional story involving Taiwan, Mongolia, East Asian politics, business, or culture.",
            "A story about China or Hong Kong, including a Hong Kong astronaut or Chinese public institution.",
        ],
        Region::SoutheastAsia => &[
            "A Southeast Asian story involving Indonesia, Vietnam, Thailand, or the Philippines.",
            "A story involving Singapore, Malaysia, Myanmar, Cambodia, Laos, or Brunei.",
            "A regional story involving ASEAN or the South China Sea.",
            "A southeast Asian story about government, economy, security, climate, or culture.",
        ],
        Region::CentralAsia => &[
            "A Central Asian story involving Kazakhstan or Uzbekistan.",
            "A story involving Kyrgyzstan, Tajikistan, or Turkmenistan.",
            "A regional story involving the Caspian Sea or central Asian trade routes.",
            "A central Asian story about politics, security, energy, economy, or society.",
        ],
        Region::Oceania => &[
            "An Australian story involving Canberra, Sydney, Melbourne, or Australian institutions.",
            "A New Zealand story involving Wellington, Auckland, or New Zealand institutions.",
            "A Pacific islands story involving Fiji, Samoa, Tonga, or Papua New Guinea.",
            "An Oceania story about politics, climate, business, health, sport, or culture.",
        ],
    }
}
