pub fn labels(sentiment: &str) -> &'static [&'static str] {
    match sentiment {
        "positive" => &[
            "Positive, good, happy, uplifting, beneficial, successful, welcomed, hopeful, and encouraging.",
            "Joy, delight, relief, praise, support, progress, improvement, prosperity, and opportunity.",
            "Victory, win, award, breakthrough, gain, growth, recovery, and good news.",
            "Financial relief, lower costs, help, support, affordability, and saving money.",
            "Kindness, generosity, care, fairness, comfort, security, wellbeing, and health improvement.",
            "Enjoyable, impressive, exciting, recommended, acclaimed, and popular.",
            "Celebration, renewal, harmony, gratitude, reassurance, and a fresh start.",
            "Good outcome, favorable result, better result, positive change, and clear benefit.",
            "Interest-free loans, investment, support, and help buying a home.",
            "Restoration, wildlife recovery, conservation success, and renewed habitat.",
            "Enjoyable streaming series, free online watch, and popular entertainment release.",
            "Business investment, supplier deals, company growth, and expansion.",
            "Sale, discount, bargain, money off, and saving on products.",
            "Developer progress, technical improvement, open source progress, and better performance.",
        ],
        "negative" => &[
            "Negative, bad, sad, harmful, tragic, worrying, upsetting, and disappointing.",
            "Death, fatal, killing, murder, violence, abuse, assault, injury, and trauma.",
            "Loss, decline, crisis, collapse, shortage, price rise, bills rise, hardship, and poverty.",
            "Fraud, corruption, negligence, failure, scandal, threat, danger, disaster, and war.",
            "Outrage, fear, anger, conflict, backlash, criticism, condemnation, and hostility.",
            "Broken, failed, suspended, banned, delayed, unsafe, regretted, and alarming.",
            "Tragedy, grief, mourning, flowers laid, body recovered from water, bereavement, fatal drowning, and dead teenager.",
            "Animal attack, dog attack, fatal dog attack, dead fish, dead sharks, local loss, and beach wash-up.",
            "Diagnosed with cancer, cancer diagnosis, serious illness, oncology, treatment, hospital, chemotherapy, alarming diagnosis, devastating cancer news, former attorney general, and frightening diagnosis.",
            "Ignored patients, NHS failures, political cuts, sackings, redundancies, civil service job losses, and planning officers.",
            "War costs, price rises, energy bills rise, energy bills, higher bills, households pay more, heat records, temperature records, climate records, and financial pain.",
            "Sports row, handshake row, confrontation, dispute, embarrassment, hostility, and controversy.",
        ],
        _ => &[],
    }
}
