pub fn labels(sentiment: &str) -> &'static [&'static str] {
    match sentiment {
        "positive" => &[
            "Socioeconomic progress and structural enhancement: major public optimization initiatives, expansion of state infrastructure, enhanced educational grants, institutional academic funding, robust state financial subsidies.",
            "Academic development and career enrichment: multi-disciplinary undergraduate advancement, vocational real-world placements, institutional student training programs, meaningful employment readiness paths.",
            "Public support and household uplift: first-time buyer assistance, home ownership help, housing support, interest-free loans, state subsidy programs, cost relief, financial access, family assistance.",
            "Commercial prosperity, excellent product discounts, and consumer retail advantages: massive holiday weekend bargain sales, spectacular e-commerce price drops, multi-percentage retail reductions, fantastic shopping deal events, clearance savings, promotional markdowns on top-rated home appliances, mattresses, footwear, televisions, and tablets.",
            "Diplomatic harmony and social cohesion: successful peaceful mediation, cross-border cooperation treaties, community solidarity, regional stabilization, civic alignment, international security partnerships.",
            "Recreational joy and cultural health: domestic comfort, positive community morale, creative restorations, cultural heritage preservation, celebratory public milestones, local leisure enhancements, gardening and outdoor backyard recreation, culinary lifestyle tips, landmark refreshes, heritage care, public preservation work.",
            "Technical innovation and operational breakthroughs: next-generation computational architectures, quantum processing achievements, pioneering engineering breakthroughs, space exploration milestones, astronaut mission selection, payload science roles, major collaborative scientific discoveries, upgraded software interfaces, creative camera tools, product launch improvements.",
            "Positive product and design momentum: electric vehicle debuts, next-generation automotive design, advanced consumer hardware launches, enthusiastic fan interest, refined aesthetics, premium engineering reveals, upgraded device performance, successful technology releases, polished design, admired styling, strong consumer reception.",
            "Scientific discovery and space mission success: astronomical research, mission launch success, payload science, astronaut launch, quantum research breakthroughs, quantum hardware, national research collaboration, major engineering milestones, observatory achievements, advanced hardware experiments, scientific achievement.",
            "Space and research triumph: astronaut mission success, space program achievement, quantum chip breakthrough, research milestone, scientific advance, laboratory success, mission accomplishment, high-impact discovery.",
            "Heritage restoration and public beautification: landmark conservation, heritage upkeep, preservation works, public art restoration, fresh restoration coatings, community care, public landmark renewal, conservation volunteers.",
            "Ecological revitalization: active wildlife preservation, habitat conservation successes, pollution remediation, successful ecosystem recovery, volunteer river monitoring, watercourse protection networks, rapid environmental issue reporting, regional land preservation, heritage restoration, conservation success.",
        ],
        "negative" => &[
            "Sovereign warfare and national security emergencies: active military targeting, state-sponsored cyber sabotage, hostile foreign subversion tactics, critical infrastructure threats, espionage intelligence warnings, cross-border military strikes, imminent security breaches, wartime economic casualties, sudden energy price shocks.",
            "Macro-economic distress and consumer inflation: escalating cost-of-living crises, soaring household utility bills, energy bill increases, regulated price cap rises, household annual cost rises, systemic supply chain collapses, global trade conflicts, punitive import tariffs, household budget pressure.",
            "Institutional failures and administrative misconduct: public trust betrayals, corporate negligence scandals, systemic medical care failures, ignored patient concerns, fatal health trust failures, cancer diagnoses, regulatory misconduct, forced administrative resignations.",
            "Extremist behavior and political radicalism: illicit partisan symbols, offensive extremist manifestations, public official misconduct controversies, intense community backlash over unethical records.",
            "Severe public tragedies, devastating loss of life, and fatal accidents: mass casualty events, lethal school building blazes, horrific structural fires, fatal injuries, ongoing body recovery rescue operations, accidental drowning disasters, sudden family bereavement crises, evacuation orders, rescue operations, combat zone casualties.",
            "Violent crimes and predatory offences: criminal physical assaults, severe public safety violations, localized sexual felonies, felony law enforcement arrests.",
            "Pathological crises, advanced malignancies, and medical suffering: cancer diagnoses, advanced malignancies, severe oncological illnesses, life-threatening physiological failures, acute clinical distress, intense psychological suffering, medical setbacks, serious diagnoses, patient distress, hospital worry, illness disclosure, diagnosis news, health setback, ousted official, dismissal news, political scrutiny, advisory controversy.",
            "Energy affordability and household pressure: utility bill increases, cost of living pressure, price cap rises, household budget strain, fuel bill shock, heating cost increases, bill shock.",
            "Local tragedy and rescue response: found dead, body recovery, search and rescue, casualty reports, missing person concerns, emergency response, incident recovery.",
            "Environmental devastation and ecological decay: hazardous chemical contamination, mass marine life mortality, toxic pollution spills, record-breaking global warmth anomalies, catastrophic planetary heat domes, illegal wildlife targeting, shooting of protected birds.",
            "Product design friction and functional degradation: highly polarizing product aesthetics, severe device operational defects, rapid battery degradation concerns, intense consumer dissatisfaction.",
            "Interpersonal discord and competitive hostility: professional handshake avoidance disputes, hostile athletic arguments, public legal rows, tense workplace altercations.",
        ],
        _ => &[],
    }
}
