pub fn labels(sentiment: &str) -> &'static [&'static str] {
    match sentiment {
        "positive" => &[
            "interest-free loans, home ownership, affordability support.",
            "astronaut, space launch, payload scientist, successful mission.",
            "prioritization, multitasking, clearer planning, useful workflow.",
            "student careers, work experience, undergraduate opportunity.",
            "streaming, free watch, popular series, entertainment.",
            "support, opportunity, help, affordability, investment, growth, improvement, progress, benefit.",
            "sale, discount, deal, bargain, saving, recommended, popular, enjoyable, useful, helpful.",
            "Public help and practical benefit: good news, welcomed support, interest-free loans, affordability, lower costs, saving money, education access, work placements, student opportunity, career support, real-world experience, business growth, supplier investment, company expansion, prosperity, and clear material benefit.",
            "Enjoyment, recommendations, and consumer value: enjoyable, impressive, exciting, acclaimed, popular, free to watch, streaming entertainment, useful buying guides, recommended products, sales, discounts, bargains, money off, comfortable home products, helpful reviews, and satisfying everyday advice.",
            "Progress and technical improvement: innovation, product launch, electric vehicles, automotive design, software progress, open source work, developer tools, better performance, successful engineering, practical technical advice, effective fixes, clearer workflows, and productivity improvement.",
            "Electric vehicle launch, car design, automotive innovation, fans, new model, and transport technology progress.",
            "Recovery, conservation, and constructive community action: restoration, renewal, wildlife recovery, habitat protection, river monitoring, pollution reporting, volunteers, conservation success, environmental improvement, public access, community effort, and protecting nature.",
            "River protection, wildlife restoration, volunteers, public access, conservation groups, and community environmental success.",
            "Achievement, discovery, and hopeful outcomes: successful launch, astronaut selection, scientific exploration, payload science, national achievement, breakthroughs, recovery, care, wellbeing improvement, fairness, security, reassurance, and encouraging future prospects.",
            "Astronaut, spaceflight, launch, scientist, exploration, achievement, mission, and discovery.",
        ],
        "negative" => &[
            "oncology, chemotherapy, cancer treatment, attorney general diagnosed with cancer.",
            "civil service cuts, job losses, public sector cuts.",
            "cancer diagnosis, serious illness, medical concern.",
            "sports row, heated exchange, dispute, controversy.",
            "flowers laid, body recovered, sexual assault, teenagers, arrested, cancer, diagnosed.",
            "Tragedy, violence, and public danger: death, fatal incidents, killing, murder, assault, sexual offences, abuse, injury, trauma, young victims, bodies recovered from water, drowning, dog attacks, school fires, casualties, students killed, search and rescue, emergency response, and unsafe situations.",
            "School fire, blaze, students killed, casualties, fatal emergency, rescue operation, and tragedy.",
            "Local grief and loss: flowers laid, teenage death, body found in water, fatal dog attack, dead fish, dead sharks, beach wash-up, local tragedy, community mourning, bereavement, and distressing local incident.",
            "Illness, care failure, and institutional harm: cancer diagnosis, diagnosed with cancer, serious illness, frightening diagnosis, hospital treatment, NHS failures, ignored patients, safeguarding failures, negligence, institutional accountability, clinical risk, patient safety failure, care quality concerns, and vulnerable people harmed.",
            "Cancer, diagnosed, serious illness, frightening health news, treatment, oncology, and medical concern.",
            "Costs, crisis, and public risk: price rises, energy bills, higher household costs, financial pressure, hardship, poverty, war impact, hostile state activity, Russia, GCHQ, national security threats, democracy pressure, infrastructure threats, intelligence warnings, espionage, heat dome, extreme heat, broken temperature records, climate danger, and alarming developments.",
            "Energy bills, bills rise, price cap, household costs, pay more, war impact, and financial pain.",
            "Wrongdoing, conflict, and legal problems: fraud, corruption, scandal, lawsuits, liability, chemical contamination, pollution damage, official investigations, arrests, criminal allegations, political cuts, sackings, redundancies, backlash, criticism, condemnation, hostility, rows, disputes, embarrassment, controversy, battery concern, Emacs, workspace manager, and technical complexity.",
        ],
        _ => &[],
    }
}
